### ISSUE TITLE
PLACEHOLDER keyword

### ISSUE THREAD

**Issue by yfried** [rhosqeauto/oldir#8]
Need a keyword (example `!placeholder`) that we use for values that should be add by user (like passwords) and kcli will throw a proper error message of missing input if this keyword is present.
The keyword can accept optional text with detailed about the expected value.

Example:

``` yaml
provisioner:
    user: yfried
    password: !placeholder "user password for openstack cloud"
```

And output will show:

```
$ kcli provisioner=openstack ...  --provisioner-site-user=yfried

Error MissingValue: Missing value for provisioner.password.
user password for openstack cloud

```
